/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JacocoSkipTest {
    @Test void test() {
        JacocoSkip test = new JacocoSkip();
        assertTrue(test.doCover(), "someLibraryMethod should return 'true'");
    }
}
